# This is a basic workflow to help you get started with Actions

name: DemoAppCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_11.4.app"
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Bundle Install
        run: bundle install

      - name: Build
        run: bundle exec fastlane test

  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    needs: [test]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_11.4.app"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundle Install
        run: bundle install
        
      - name: Build
        run: bundle exec fastlane build
